version: '3.7'

services:
    embedded-highlevel:
        image: embedded-test
        container_name: embedded-test
        privileged: true
        build:
            context: .
            dockerfile: dockerfile
            network: host
        network_mode: "host"
